"""Change embedding dimension to 1024 for YandexEmbeddings

Revision ID: 66b3cd5606cf
Revises: 65c9aba432dd
Create Date: 2025-05-04 17:20:34.925687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b3cd5606cf'
down_revision: Union[str, None] = '65c9aba432dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
